---
title: "stl_lead_inequity"
author: "Allie Cole"
date: "8/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(skimr)
```

## getting the data 

```{r}
stl_lead <- read_delim(here::here("data", "stl_blood_lead.csv"), delim = ";")
stl_lead <- stl_lead %>% clean_names()
```

## creating a new column 

```{r}
stl_lead_prop <- stl_lead %>% 
  mutate(prop_white = white/ total_pop * 100) %>% 
  mutate(pct_elevated = str_replace(pct_elevated,
                                    pattern = ",", 
                                    replacement = ".")) %>%  #will overwrite it
  mutate(pct_elevated = as.numeric(pct_elevated))
```

## creating a new scatterplot 

```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated, y = prop_white)) +
  geom_point(alpha = .6, color = "purple") +
  theme_minimal() +
  labs(title = "Elavated Lead Blood Levels by Race ",
       x = "Percent of Census Identifying as White ",
       y = "Percent of Children with Elavted Lead Blood Levels")

stl_lead_plot

ggsave(here::here("figs", "children_lead_plot.jpg"), plot = stl_lead_plot)
```

## making a histogram 

```{r}
pct_elev_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram(color = "pink", fill = "purple", alpha = 0.4) +
  theme_minimal() +
  labs(title = "Elevated Levels of Lead in Blood ",
       x = "Percentance Elevated ")

pct_elev_plot

ggsave(here::here("figs", "pct_evl_hist.jpg"), plot = pct_elev_plot, height = 7, width = 7)
```











